### ISSUE TITLE
Problem mit Sketch

### ISSUE THREAD

**Issue by GregorAUT** [danrauch/arduino-cerea-remote-control#12]
1: Ich hab die Bauteile so zusammengebaut wie es beschrieben wurde.
2: Download der cerea remote control Datei (welche Version?: 0.1.0, 0.2.0, 0.2.1)
3: Download der 4 Zip Dateien aus der Filebase
4: Öffnen der Cerea Remote Control Datei mit der Arduino Software
5: Auswahl des richtigen Ports
6: 4 zip Dateien in Bibliothek einbinden.
7: Sketch hochladen

Dann kommt folgender Fehler:

![D1BD40F9-95F4-4A22-8E87-FA0AD59EE3CB](https://user-images.githubusercontent.com/51210719/60611029-9d9de680-9dc5-11e9-8b85-90034490d5d5.jpeg)

Woran kann es liegen?

**Comment by danrauch** [comment]
Release 0.2.1 ist die aktuelle Version, die auch verwendet werden sollte.

Das ist ein Fehler in der TFT-LCD Bibliothek von Adafruit. Diese wird von den anderen Abhängigkeiten genutzt. Haben Sie von MCUFRIEND_kbv und Adafruit_GFX Library die jeweilig akutellen **Release**versionen gezogen?

**Comment by GregorAUT** [comment]
Guten Tag!

Habs hinbekommen.

Musste die GFX Datei downgraden auf Version 1.5.3.

Freundliche Grüße

**Comment by danrauch** [comment]
Vielen Dank für die Info! Interessant, dass Adafruit hier die Kompatibilität beim Versionssprung gebrochen hat...
