### ISSUE TITLE
Sketchänderung; automatisches Wenden!

### ISSUE THREAD

**Issue by GregorAUT** [danrauch/arduino-cerea-remote-control#13]
Hallo!

Ich möchte 2 Tasten für links und rechts wenden verwenden.
Wie müsste denn dazu der Sketch an welcher Stelle abgeändert werden?

Danke!

Freundliche Grüße,
Gregor S

**Comment by danrauch** [comment]
Hallo Gregor,

man müsste dazu die letzten beiden Einträge im SDOSE Ausgabestring (im Moment steht da fix zwei mal „0“) mit Leben füllen:

sprintf(cerea_command_out, "@SDOSE;%d;0;0;0;%d;%d;%d;%d;%d;**0**;**0**;END",...

Das kann man 1 zu 1 so machen wie das schon bei „links“ und „rechts“ umgesetzt ist. Die Datenstruktur für den aktuellen Cereastatus sieht sogar schon entsprechende Einträge vor (turn_left, turn_right).

VG

**Comment by GregorAUT** [comment]
Ich verwende derzeit die Version 0.2.1.

Kann leider die genannten Stellen nicht finden im Sketch, welche zu ersetzen sind.

Evtl. diese?; (siehe Bild)


Und wie genau muss ich hier die Textstellen ändern?

Bin leider noch nicht sehr geübt in der Arduino Programmierung.

Danke! 
Freundliche Grüße,
Gregor
![image](https://user-images.githubusercontent.com/51210719/60983757-d34d4d00-a33a-11e9-8090-95cd3863dbb7.jpg)

**Comment by GregorAUT** [comment]
![image](https://user-images.githubusercontent.com/51210719/60984062-5a9ac080-a33b-11e9-86bf-167e1b6aed41.jpg)


Ah, habs übersehen.

Und was muss ich hier jetzt genau alles anpassen im Sketch?

**Comment by danrauch** [comment]
Als erstes müsste man sich überlegen, wie man die Funktion bedienbar macht. Da gibt es generell folgende Möglichkeiten:
- Man führt 2 weitere Touchbuttons ein. Dies wäre einfach zu bewerkstelligen; jeder Button müsste aber dafür kleiner werden.
- Man nutzt 2 vorhandene Buttons, was ebenfalls trivial wäre. Die überschriebenen Funktionen würden so aber natürlich nicht mehr zur Verfügung stehen.
- Man führt eine zweite "Seite" mit den zusätzlichen Buttons und die entsprechende Seitennavigation ein. Das wäre eher aufwändig.

Die eigentliche Funktionalität ist im jedem Fall so nachzurüsten:
1. Buttons erstellen (äquivalent zu anderen Buttons). Diese könnten z.B. `BUTTON_TURN_LEFT` und `BUTTON_TURN_RIGHT` heißen.
2. Bei Buttondruck "turn_left" bzw. "turn_right" der cerea_commands-Struktur in der switch-Anweisung auf true setzen, z.B.:
     ``` C
    case BUTTON_TURN_LEFT: cerea_commands.turn_left = true; break;
    case BUTTON_TURN_RIGHT: cerea_commands.turn_right = true; break;
    ```
3. Status der Flags zur Ausgabe hinzufügen:
    ``` C               
    sprintf(cerea_command_out, "@SDOSE;%d;0;0;0;%d;%d;%d;%d;%d;%d;%d;END", cerea_commands.marc,
                                                                           cerea_commands.A, 
                                                                           cerea_commands.B,
                                                                           cerea_commands.auto_on,
                                                                           cerea_commands.left,
                                                                           cerea_commands.right,
                                                                           cerea_commands.turn_left,
                                                                           cerea_commands.turn_right);
    ```
4. Flags auf false zurücksetzen, äquivalent zu z.B. left.

**Comment by GregorAUT** [comment]
Hallo!

Danke erstmal für deine Ausführungen!

Also ich denke, dass die zweite Lösung die praktikabelste wäre.

Wenn ich beispielsweise keine Relais ansteuern möchte dann wäre es ja sinnvoll die Buttons „aktiv“ und „streuen“ zu ersetzen.

Und andernfalls könnten die Tasten „links“ und „rechts“ ersetzt werden, da diese wahrscheinlich am wenigsten oft benötigt werden.

Wäre es denn recht ein Aufwand, wenn du nochmal eine Version etwas umschreibst wie oben erwähnt und hochlädst? :-)   Natürlich nur wenn es die Zeit erlaubt.

**Comment by danrauch** [comment]
In diesem branch liegt eine etwas abgewandelte v0.2.1, welche die Relaisfunktionen mit Wenden ersetzt:
https://github.com/danrauch/arduino-cerea-remote-control/tree/turn_no_relais

Konnte es aber nicht testen...

**Comment by GregorAUT** [comment]
Super, danke! 

Werd ich gleich mal testen.

Freundliche Grüße,
Gregor

**Comment by GregorAUT** [comment]
Hallo Daniel!

Hab's soeben getestet. 
Folgender Fehler wird angezeigt beim hochladen;


Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Users\grego\Downloads\arduino-cerea-remote-control-turn_no_relais\arduino-cerea-remote-control-turn_no_relais\cerea-remote\cerea-remote.ino: In function 'void loop()':

cerea-remote:296:22: error: 'BUTTON_RELAY_AUTO' was not declared in this scope

             if (b != BUTTON_RELAY_AUTO) {

                      ^

exit status 1
'BUTTON_RELAY_AUTO' was not declared in this scope

**Comment by danrauch** [comment]
Das war noch vom alten drin, tatsächlich. Ist behoben.

**Comment by GregorAUT** [comment]
Hab nun den Sketch hochgeladen und getestet.
Das ging schon mal, und auch die Oberfläche sieht sehr gut aus.

Jedoch gibts noch zwei Probleme:
Die 2 Tasten zum Wenden funktionieren noch nicht. Bei Tastendruck reagiert das Bedienelement garnicht.
Alle anderen Tasten funktionieren in Cerea.

Außerdem gibt es keine Vibrationsrückmeldung mehr bei Betätigung sämtlicher Tasten.

Lg

**Comment by danrauch** [comment]
Ist behoben, sorry, ich hab zur Zeit keine Hardware zum testen verfügbar - bin quasi blind :-)
War jedoch nur ne Anzeigesache. Den Befehl zum Wenden sollte das Programm dennoch geschickt haben.
Falls Cerea das nicht annimmt, haben die das noch nicht implementiert...
Auch die Vibration sollte funktionieren - hier Achtung: Sie müssen `#define VIBRATION_MOTOR_PIN LED_BUILTIN` entsprechend Ihrem Anschlussschema anpassen. Z.B. meist nutzen die Leute Pin 13. Dann muss es so aussehen: `#define VIBRATION_MOTOR_PIN 13`

**Comment by GregorAUT** [comment]
Ok., kein Problem.
Hab ja alles zum testen. :-)

Ok., das mit dem Vibrations PIN hätte ich wissen können.

Funtioniert jetzt soweit.
Er nimmt jetzt auch den Tastendruck auf links und rechts wenden wahr.
Jedoch kommt noch nix bei Cerea an.

Muss ich evtl. in Cerea Einstellungen ändern?

Lg

**Comment by GregorAUT** [comment]
...Zusatzinfo!

Bei Cerea ist in der Config „o“ als turn_left und „p“ als turn_right Befehl angegeben!
Mit einer Tastatur bei Betätigung der Tasten „p“ und „o“ funktioniert das automatische wenden!

Danke für deine Bemühungen!

**Comment by danrauch** [comment]
Kann keinen Fehler im Code mehr feststellen. Im Forum schreiben die Leute, dass Wenden in diesem Zusammenhang „ohne Funktion“ ist: https://cerea-forum.de/forum/index.php?thread/91-befehle-für-tastatureingaben-von-arduino-zu-cerea/
Das könnte aber auch noch nicht der Weisheit letzter Schluss sein... evtl. nochmals im Forum nachfragen, ob wer die Lösung kennt.
Ich selber hab kein Cerea, kann es also nicht testen...

**Comment by GregorAUT** [comment]
Ok., dann probier ich selbst nochmal alles Mögliche durch!

Und dass man einfach den Buchstaben „o“ und „p“ rausgibt bei Tastendruck, als ob man eine Tastatur betätigt würde nicht funktionieren denkst du?

Bei einer Tastatur funktioniert es nämlich.

Danke auf jeden Fall für deine Bemühungen!

Hier noch das Video:
https://youtu.be/sUeeW8SyTd4

**Comment by danrauch** [comment]
Leider bewegen wir uns hier in einen ganz anderen Context wie eine Tastatur.
Wie gesagt, das Forum könnte weiterhelfen. Ich schließe den Issue, da der Sketch wahrscheinlich nicht das Problem ist.
